// Models with reasoning capabilities
export const REASONING_MODELS = [
  "deepseek-ai/DeepSeek-R1",
  "deepseek-reasoner",
  "deepseek-chat",
  "deepseek-coder",
  "openrouter:deepseek/deepseek-r1:free",
  "openrouter:deepseek/deepseek-reasoner",
  "openrouter:deepseek/deepseek-chat",
  "openrouter:qwen/qwen3-30b-a3b-thinking-2507",
  "openrouter:qwen/qwen3-235b-a22b-thinking-2507",
  "openrouter:thudm/glm-4.1v-9b-thinking",
  "openrouter:mistralai/magistral-medium-2506:thinking",
];

// Popular models to show first for faster selection
export const POPULAR_MODELS = [
  "gpt-5-nano",
  "gpt-4o",
  "claude-opus-4",
  "gpt-4.1",
  "gemini-1.5-flash",
  "mistral-medium",
  "deepseek-chat",
];

// Base models list without the reasoning models that will be added after
const BASE_MODELS = [
  "gpt-5-2025-08-07",
  "gpt-5",
  "gpt-5-mini-2025-08-07",
  "gpt-5-mini",
  "gpt-5-nano-2025-08-07",
  "gpt-5-nano",
  "gpt-5-chat-latest",
  "gpt-4o",
  "gpt-4o-mini",
  "o1",
  "o1-mini",
  "o1-pro",
  "o3",
  "o3-mini",
  "o4-mini",
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-4.1-nano",
  "gpt-4.5-preview",
  "claude-opus-4-1-20250805",
  "claude-opus-4-1",
  "claude-opus-4-20250514",
  "claude-opus-4",
  "claude-opus-4-latest",
  "claude-sonnet-4-20250514",
  "claude-sonnet-4",
  "claude-sonnet-4-latest",
  "claude-3-7-sonnet-20250219",
  "claude-3-7-sonnet-latest",
  "claude-3-5-sonnet-20241022",
  "claude-3-5-sonnet-latest",
  "claude-3-5-sonnet-20240620",
  "claude-3-haiku-20240307",
  "deepseek-ai/DeepSeek-R1",
  "cartesia/sonic",
  "deepseek-ai/DeepSeek-R1-DE",
  "cartesia/sonic-2",
  "togethercomputer/MoA-1",
  "meta-llama/Meta-Llama-Guard-3-8B",
  "meta-llama/LlamaGuard-2-8b",
  "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
  "meta-llama/Llama-3.3-70B-Instruct-Turbo",
  "moonshotai/Kimi-K2-Instruct",
  "openai/gpt-oss-20b",
  "moonshotai/Kimi-K2-Instruct-0905",
  "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
  "meta-llama/Llama-3.2-3B-Instruct-Turbo",
  "Salesforce/Llama-Rank-V1",
  "mistralai/Mistral-Small-24B-Instruct-2501",
  "mistralai/Mistral-7B-Instruct-v0.3",
  "openai/whisper-large-v3",
  "mistral-large-latest",
  "mistral-medium-2508",
  "mistral-medium-latest",
  "mistral-medium",
  "mistral-small",
  "mistral-small-2312",
  "grok-beta",
  "grok-vision-beta",
  "grok-3",
  "grok-3-fast",
  "grok-3-mini",
  "grok-3-mini-fast",
  "grok-2-vision",
  "grok-2",
  "deepseek-chat",
  "deepseek-reasoner",
  "gemini-1.5-flash",
  "gemini-2.0-flash",
];

// Full list of models with reasoning models added
export const AI_MODELS: string[] = [
  ...BASE_MODELS,
  ...REASONING_MODELS.filter((model) => !BASE_MODELS.includes(model)),
];
